name: Cloudflare Pages

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Trunk
        uses: jetli/trunk-action@v0.4.0
      - name: Install TailwindCSS CLI
        uses: supplypike/setup-bin@v3
        with:
          uri: https://github.com/tailwindlabs/tailwindcss/releases/download/v3.3.3/tailwindcss-linux-x64
          name: tailwindcss
          version: '3.3.3'

      - name: Build with Trunk
        run: trunk build --release

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: jugo-leptos
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
